/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aminoacid;
import java.util.*;

/*R,H,K
N,Q,W, */

public class App {

    private static List<AminoEntry> aminoList = new ArrayList<AminoEntry>();
    private static AminoWindow aminoWindow;
    public static void main(String[] args) {
      AminoModel aminoModel = new AminoModel(aminoList);
      aminoWindow = new AminoWindow(aminoModel);
  }
}
